#
#
# Source: https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/
#   - Now you can include completely new combinations and even specify all of your matrix legs with include.
#   - The Actions expression language has a fromJSON(value) method that can take a stingified JSON object and bind it to a property.
#   - Combining this with run-tf-matrix.outputs you can build a workflow that has a fully dynamic matrix.
#

name: terraform
on: push
jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: checkout code
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: test changed files
      id: check-terraform-folder-for-changed-files
      # Only run terraform IF tf files changed: https://github.com/tj-actions/changed-files
      # output: all_changed_and_modified_files (list of all files changed/modified)
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          terraform/

    - name: set matrix
      id: set-matrix
      # set JSON-matrix as output for usage in other jobs/steps
      # source: https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script
      run: |
        FILE_LIST=$(echo ${{ steps.check-terraform-folder-for-changed-files.outputs.all_modified_files }} | sort -u)
        DIR_LIST=$(dirname $FILE_LIST | sort -u)
        echo "::debug::Found folder list:"
        echo "::debug::$DIR_LIST"
        JSON="{\"include\":["
        for FOLDER in $(echo $DIR_LIST); do
          echo " *** Adding folder:$FOLDER:"
          JSON+="{\"folder\": \"$FOLDER\"},"
        done

        # Remove last "," and add closing brackets
        if [[ $JSON == *, ]]; then
          JSON="${JSON%?}"
        fi
        JSON="$JSON]}"
        echo "::debug:: created JSON matrix"
        echo $JSON | jq
        # Set json output to be uses as matrix strategy.
        echo "::set-output name=matrix::$( echo "$JSON" )"

  run-tf-matrix:
    needs: create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.create-matrix.outputs.matrix)}}
    steps:
    - name: show tf-folder matrix
    - run: |
        echo " folder:${{ matrix.folder}}"

    - name: Terraform init
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.6
      run: terraform -chdir ${{ matrix.folder}} init

    - name: Terraform fmt
      id: fmt
      run: terraform -chdir ${{ matrix.folder}} fmt -check
