#
#
# Source: https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/
#   - Now you can include completely new combinations and even specify all of your matrix legs with include.
#   - The Actions expression language has a fromJSON(value) method that can take a stingified JSON object and bind it to a property.
#   - Combining this with run-matrix.outputs you can build a workflow that has a fully dynamic matrix.
#

name: build
on: push
jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  run-matrix:
    needs: create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.create-matrix.outputs.matrix)}}
    steps:
    - run: |
        echo " project:${{ matrix.project}}"
        echo " config:${{ matrix.config}}"
