#
#
# Source: https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/
#   - Now you can include completely new combinations and even specify all of your matrix legs with include.
#   - The Actions expression language has a fromJSON(value) method that can take a stingified JSON object and bind it to a property.
#   - Combining this with run-matrix.outputs you can build a workflow that has a fully dynamic matrix.
#

name: terraform
on: push
jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: checkout code
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: test changed files
      id: check-terraform-folder-for-changed-files
      # Only run terraform IF tf files changed: https://github.com/tj-actions/changed-files
      # output: all_changed_and_modified_files (list of all files changed/modified)
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          terraform/

    - name: set matrix
      id: set-matrix
      # set JSON-matrix as output for usage in other jobs/steps
      # source: https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script
      run: |
        FILE_LIST=$(echo ${{ steps.check-terraform-folder-for-changed-files.outputs.all_modified_files }} | sort -u)
        DIR_LIST=$(dirname $FILE_LIST | sort -u)
        echo "$DIR_LIST"
        JSON="{\"include\":["
        for FOLDER in $(echo $DIR_LIST); do
           # Add build to the matrix only if it is not already included
          JSONline+="{\"folder\": \"$FOLDER\"},"
          if [[ "$JSON" != *"$JSONline"* ]]; then
            JSON="$JSON$JSONline"
          fi
        done

        # Remove last "," and add closing brackets
        if [[ $JSON == *, ]]; then
          JSON="${JSON%?}"
        fi
        JSON="$JSON]}"
        echo $JSON
        # Set output
        echo "::set-output name=matrix::$( echo "$JSON" )"

  run-matrix:
    needs: create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.create-matrix.outputs.matrix)}}
    steps:
    - run: |
        echo " project:${{ matrix.folder}}"
