#
# Run Terraform in a folder-matrix.
#

name: Terraform-Matrix
on:
  # Workflow runs on all pushes
  push:

jobs:
  tf-matrix:
    name: TF matrix
    ## FIXME: replace version with @main
    uses: radiomix/gh-actions-matrix-test/.github/workflows/terraform-matrix-reusable-workflow.yaml@tf-matrix

  # tf-run-matrix:
  #   name: run TF matrix
  #   needs: tf-create-matrix
  #   ## FIXME: replace version with @main
  #   uses: radiomix/gh-actions-matrix-test/.github/workflows/terraform-base-reusable-workflow.yaml@tf-matrix
  #   with:
  #     terraform-folder: ${{ fromJSON(needs.tf-create-matrix.outpus.matrix.folder) }}
