#
#
# Source: https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/
#   - Now you can include completely new combinations and even specify all of your matrix legs with include.
#   - The Actions expression language has a fromJSON(value) method that can take a stingified JSON object and bind it to a property.
#   - Combining this with run-tf-matrix.outputs you can build a workflow that has a fully dynamic matrix.
#

name: create-terraform-folder-matrix
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  create-terraform-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-tf-matrix.outputs.matrix }}
      run_terraform: ${{ steps.set-tf-matrix.outputs.run_terraform }}
    steps:
    - name: checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: test changed files
      id: check-terraform-folder-for-changed-files
      # Only run terraform IF tf files changed: https://github.com/tj-actions/changed-files
      # output: all_changed_and_modified_files (list of all files changed/modified)
      uses: tj-actions/changed-files@v13
      with:
        files: |
          terraform/**/*tf

    - name: set matrix
      id: set-tf-matrix
      # set JSON-matrix as output for usage in other jobs/steps
      # source: https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script
      run: |
        FILE_LIST=$(echo ${{ steps.check-terraform-folder-for-changed-files.outputs.all_modified_files }} | sort -u)
        DIR_LIST=$(dirname $FILE_LIST | sort -u)
        echo " *************"
        echo "$DIR_LIST"
        echo " *************"
        JSON="{\"include\":["
        for FOLDER in $(echo $DIR_LIST); do
          echo " *** Adding folder:$FOLDER:"
          JSON+="{\"folder\": \"$FOLDER\"},"
        done

        # Remove last "," and add closing brackets
        if [[ $JSON == *, ]]; then
          JSON="${JSON%?}"
        fi
        JSON="$JSON]}"
        echo " *************"
        echo $JSON  | jq
        echo " *************"
        # Set output
        echo "::set-output name=matrix::$( echo "$JSON" )"

        # Check empty matrix
        echo ::set-output name=run_terraform::'NO'
        for file in ${{ steps.check-for-changed-files.outputs.all_changed_files }}; do
          echo "File $file was changed"
          run_terraform=true
        done
        if [[  $run_terraform  ]]; then
          echo ::set-output name=run_terraform::${{ 'YES' }}
        fi
    - name: show folder
      run: |
        echo " Run Terraform:'${{ steps.set-tf-matrix.outputs.run_terraform}}'"
        echo " folder:'${{ steps.set-tf-matrix.outputs.matrix}}'"
        echo " Do we have changed-files:'${{ steps.check-terraform-folder-for-changed-files.outpus.any_changed }}'"

  run-tf-matrix:
    needs: create-terraform-matrix
    # See: https://github.community/t/github-actions-show-pipeline-failed-with-red-cross-while-all-jobs-succeeded/189036/3
    # if: ${{ needs.create-terraform-matrix.outputs.matrix != ''}}
    if: ${{ needs.create-terraform-matrix.outputs.run_terraform != 'YES'}}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.create-terraform-matrix.outputs.matrix)}}
    # prevent this job from running with an empty matrix: It would fail.

    steps:
      - name: show folder
        run: |
          echo " folder:${{ matrix.folder}}"
