##
##  Terraform workflow (c) 2021 by Elemica Inc.
##    - Create a JSON-matrix of folders with changed TF-files.
##    - Run the TF commands per JSON-matrix for each folder with changed TF-files.
##  Source: https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/
##  Maintainer: SRE-team Elemica Inc.
##

name: terraform-matrix

# Controls when the action will run
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Create a JSON-matrix of all folders with changed TF files.
  create-tf-matrix:
    runs-on: ubuntu-latest
    outputs:
      # Remember JSON-matrix for later usage.
      matrix: ${{ steps.set-tf-matrix.outputs.matrix }}
      # True/False ONLY_IFF TF file changed
      run_terraform: ${{ steps.set-tf-matrix.outputs.check-matrix }}
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
          # Only partly explained: https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          # Nice explanation of 'git checkout HEAD^1': https://stackoverflow.com/questions/2221658/whats-the-difference-between-head-and-head-in-git
          # fetch-depth 0 = full history, 1 = only last commit (default), 2 = HEAD^ (last PARENT commit or merge in)
        fetch-depth: 2

    - name: Check changed files
      # Check for changed files: https://github.com/tj-actions/changed-files
      # Action outputs: 'all_changed_and_modified_files'
      id: check-for-changed-files
      uses: tj-actions/changed-files@v13
      with:
        files: |
          terraform/**/*.tf

    - name: set TF matrix
      id: set-tf-matrix
      # Create a JSON-matrix of FOLDER WITH CHANDED TF FILES as outputs.matrix for usage in other jobs/steps
      # Source: https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script
      run: |
        FILE_LIST=$(echo ${{ steps.check-for-changed-files.outputs.all_modified_files }} | sort -u)
        DIR_LIST=$(dirname $FILE_LIST | sort -u)
        echo " *************"
        echo "$DIR_LIST"
        echo " *************"
        JSON="{\"include\":["
        for FOLDER in $(echo $DIR_LIST); do
          echo " *** Adding folder:$FOLDER:"
          JSON+="{\"folder\": \"$FOLDER\"},"
        done

        # Remove last "," and add closing brackets
        if [[ $JSON == *, ]]; then
          JSON="${JSON%?}"
        fi
        JSON="$JSON]}"
        echo " *************"
        echo $JSON  | jq
        echo " *************"
        # Set output
        echo "::set-output name=matrix::$( echo "$JSON" )"

    - name: Check matrix
      id: check-matrix
      # FIXME: sieve out other_changed_files IFF NOT only_changed
      if: (! ${{ steps.check-for-changed-files.outputs.only_changed }} )
      # set an output to decide wheather to trigger TF commands
      run: |
        echo "'${{ steps.set-tf-matrix.outputs.matrix }}'"
        run_matrix=false
        for file in ${{ steps.check-for-changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

####################################
# run tf-matrix as reusable workflow
####################################
  run-tf-matrix:
    needs: create-tf-matrix
    # prevent this job from running with an empty matrix: It would fail.
    # See: https://github.community/t/github-actions-show-pipeline-failed-with-red-cross-while-all-jobs-succeeded/189036/3
    if: ${{ needs.tf-matrix.outputs.matrix != ''}}
    strategy:
      matrix: ${{fromJson(needs.create-tf-matrix.outputs.matrix)}}

    steps:
      - name: call-reusable-workflow
        ## FIXME: Before merging in: replace @this/branch-name with @master
        uses: radiomix/gh-actions-matrix-test/.github/workflows/terraform-base-reusable-workflow.yaml@tf-matrix
        with:
          terraform-folder: ${{fromJson(needs.create-tf-matrix.outputs.matrix)}}
          cli_config_credentials_token: ${{ my-secret }}
